name: Run Unit Tests

on: [push, pull_request, fork, workflow_dispatch]


jobs:
  non_sdk_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        shell: bash
        run: |
          echo "Building docker image and running unit tests"
          make docker-build
          make docker-unit-gha
